window.PROMPTS_ZH = {
"A person bends forward, lifts their right leg, and then extends their right arm upwards.":"一个人向前弯腰，抬起右腿，然后向上伸出右臂。",
"A person lies on a hospital bed, moving their right arm slightly upward and then downward.":"一个人躺在病床上，右臂轻轻向上移动，然后向下放回。",
"A person stands still and gestures with both hands, moving them up and down.":"一个人站在原地，双手上下移动着做手势。",
"A person squats down, adjusts their jacket, and then stands up while holding an object in both hands.":"一个人蹲下，整理外套，然后双手拿着一个物体站起来。",
"A person raises their right arm upwards and then lowers it back down.":"一个人向上举起右臂，然后将其放下。",
"A person walks forward, turns his head to the left, and continues walking.":"一个人向前走，向左转头，然后继续行走。",
"A person walks forward, turns her head to the left, and continues walking.":"一个人向前走，向左转头，然后继续行走。",
"A person stands still and raises their right arm, pointing forward.":"一个人站在原地，抬起右臂指向前方。",
"A person stands still and extends their right arm forward, holding a glowing object.":"一个人站在原地，向前伸出右臂，手持一个发光的物体。",
"A person walks forward, swings their arms slightly, and then continues walking.":"一个人向前走，轻轻摆动双臂，然后继续行走。",
"A person stands still and turns his head slightly to the right.":"一个人站在原地，头部略微向右转。",
"A person stands still and turns their head slightly to the right.":"一个人站在原地，头部略微向右转。",
"A person exits the van, walks forward, and then turns their head to the right.":"一个人走出厢式车，向前走，然后向右转头。",
"A person sits on a couch and turns their head slightly to the right.":"一个人坐在沙发上，头部略微向右转。",
"A person walks forward along the sidewalk, maintaining a steady pace.":"一个人沿人行道向前走，保持平稳的步伐。",
"A person stands still and raises their right hand to cover their face, then lowers it.":"一个人站在原地，抬起右手遮住脸，然后放下右手。",
"A person sits in a car, adjusts their hair with their right hand, and then leans forward slightly.":"一个人坐在车里，用右手整理头发，然后稍微向前倾身。",
"A person sits in a chair, gestures with both hands, and then leans slightly forward.":"一个人坐在椅子上，双手做手势，然后稍微向前倾身。",
"A person leans against the refrigerator, places their left hand on the door, and then turns their head slightly to the left.":"一个人靠着冰箱，将左手放在冰箱门上，然后略微向左转头。",
"A person stands still and then walks forward, holding a flashlight in their right hand.":"一个人先站在原地，然后向前走，右手拿着手电筒。",
"A person gestures with their hands, moving them in a circular motion as they speak.":"一个人一边说话，一边用双手做画圈的手势。",
"A person stands still and gestures with their hands while speaking.":"一个人站在原地，一边说话一边用双手做手势。",
"A person adjusts their scarf by pulling it closer to their chest and then smooths it out with both hands.":"一个人将围巾拉近胸前，然后用双手将其整理平整。",
"A person squats down, picks something up from the floor, and then stands up.":"一个人蹲下，从地上捡起东西，然后站起来。",
"A person walks forward, adjusts their hair with their right hand, and continues walking.":"一个人向前走，用右手整理头发，然后继续行走。",
"A person stands in front of the mirror, adjusts their hair with both hands, and then steps back slightly.":"一个人站在镜子前，用双手整理头发，然后稍微向后退一步。",
"A person stands still and turns their head from side to side.":"一个人站在原地，头部左右转动。",
"A person stands still and turns their head to the right.":"一个人站在原地，向右转头。",
"A person walks forward, extends their right arm outward, and then brings it back inwards.":"一个人向前走，向外伸出右臂，然后将右臂收回。",
"A person stands still and turns his head to the left.":"一个人站在原地，向左转头。",
"A person in a white protective suit runs forward, extends their arms outward, and then jumps into an elevator.":"一个穿白色防护服的人向前跑，向外伸出双臂，然后跳进电梯。",
"A person stands still and adjusts their hair with their right hand.":"一个人站在原地，用右手整理头发。",
"A person in a suit walks forward, turns his head to the left, and continues walking.":"一个穿西装的人向前走，向左转头，然后继续行走。",
"A person sits on a stool, moves their left hand towards their face, and then places it back on the instrument.":"一个人坐在凳子上，将左手移向脸部，然后将左手放回乐器上。",
"A person leans forward, adjusts their position, and then sits back down.":"一个人向前倾身，调整位置，然后重新坐下。",
"A person walks forward, swinging their arms naturally.":"一个人向前走，双臂自然摆动。",
"The camera starts with a boom top shot.":"相机以向上升降（boom top）的镜头开始。",
"The camera starts with a pull-out motion throughout the entire shot.":"相机从开始并在整个镜头中持续后拉，远离主体。",
"The camera moves right with a trucking motion during the entire shot.":"相机在整个镜头中持续向右横移。",
"The camera begins with a boom bottom motion. (Entire shot)":"相机从开始并在整个镜头中向下降低（boom bottom）。",
"The camera performs a pull-out motion throughout the entire shot.":"相机在整个镜头中持续后拉，远离主体。",
"The camera initiates a pull-out motion throughout the entire shot.":"相机从开始并在整个镜头中持续后拉，远离主体。",
"The camera starts with a boom bottom camera motion.":"相机以向下降低（boom bottom）的运动开始。",
"The camera begins with a pull-out motion throughout the entire shot.":"相机从开始并在整个镜头中持续后拉，远离主体。",
"The camera moves right (trucking) throughout the shot.":"相机在整个镜头中持续向右横移。",
"The camera executes a push-in motion throughout the entire shot.":"相机在整个镜头中持续向前推进，靠近主体。",
"The camera moves in for a push-in throughout the shot.":"相机在整个镜头中持续向前推进，靠近主体。",
"The camera remains static throughout the entire shot.":"相机在整个镜头中保持静止。",
"The camera moves in for a close-up throughout the shot.":"相机在整个镜头中向前靠近主体，形成近景。",
"The camera starts with a boom top motion for the entire duration of the shot.":"相机从开始并在整个镜头中向上升高（boom top）。",
"The camera maintains a low angle, hovering just above the ground throughout the shot.":"相机在整个镜头中保持贴近地面的低角度。",
"The camera gradually moves closer to the subject throughout the shot.":"相机在整个镜头中逐渐靠近主体。",
"The camera moves laterally to the right throughout the shot.":"相机在整个镜头中持续向右横移。",
"The camera moves right along a dolly or truck during the entire shot.":"相机在整个镜头中沿轨道或移动平台向右移动。"
};
